services:
  bot:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: reminder-bot
    env_file: 
    - ../.env
    depends_on:
    - db

  db:
    image: postgres:17
    container_name: reminder-docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: