services:
  bot:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: reminder-bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN:?BOT_TOKEN is required}
      DEBUG: ${DEBUG:-false}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB?POSTGRES_DB is required}
      POSTGRES_HOST: ${POSTGRES_HOST
      POSTGRES_PORT: 5432
    depends_on:
    - db

  db:
    image: postgres:17
    container_name: reminder-docker
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB?POSTGRES_DB is required}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
